### ISSUE TITLE
Evaluate adding a simple implementation of data adaptive feature weights

### ISSUE THREAD

**Issue by sjsw** [forestry-labs/Rforestry#10]
The idea is:
(1) train a forest with a smallish number of trees
(2) see how often each feature is split on in this forest
(3) train a new forest with feature weights in proportion to the probabilities each feature was split on in the original forest
(4) combine the trees from (1) and (3) into single forest to produce a final prediction. 

This idea arose from a conversation with Jas.

**Comment by theo-s** [comment]
This seems like a good idea. It could also be expanded to include deep/normal featureWeight options based on split proportions at different levels in the forest. I will work on a full wrapper to add this adaptive functionality. 

If you want to test out a prototype of this, I have pushed a new helper function- getSplitProps() to the `clean_forestry` branch, which will return the splitting proportions in a trained forest. Using the result from this, it should be easy to implement a first draft in R.

**Comment by theo-s** [comment]
There is now a prototype implemented of this idea in the `adaptiveForestry` class. Further features can be added to this class to flesh out the functionality.
