### ISSUE TITLE
Plotting with linear = TRUE sometimes fails

### ISSUE THREAD

**Issue by sjsw** [forestry-labs/Rforestry#15]
When plotting a model with linFeats = TRUE, I get the error: `Error in elnet(x, is.sparse, ix, yx, y, weights, offset, type.gaussian, y is constant; gaussian glment fails at the standardization step`

Here is code that produces it, largely taken from an example in `?forestry`. 

```
n <- c(100)
a <- rnorm(n)
b <- rnorm(n)
c <- rnorm(n)
y <- 4*a + 5.5*b - .78*c
x <- data.frame(a,b,c)

forest <- forestry(
  x,
  y,
  ntree = 10,
  replace = TRUE,
  maxDepth = 100,
  nodesizeStrictSpl = 1,
  nodesizeStrictAvg = 1,
  nthread = 2,
  linear = TRUE
)

plot(forest)
```

**Comment by sjsw** [comment]
It looks like this was actually caused by an outdated version of glmnet.

**Comment by sjsw** [comment]
Actually it seems it is not related to glment version, rather the error is intermittent because it depends on the seed used to construct the forest. I think it probably arises when a tree contains leaves that are grown to purity, which causes glmnet to fail when called in the plotting method. This could be fixed by patching the plotting function to not call glmnet when the variance of the outcome in a leaf is zero.

**Comment by linanqiu** [comment]
For the case where you have this error:

```
Error in if (any(lambda < 0)) stop("lambdas should be non-negative") : 
  missing value where TRUE/FALSE needed
```

The cause is:

https://github.com/forestry-labs/Rforestry/blob/cecf729b2c48afdcd09a917ceb1867bae99457d4/R/plottree.R#L238-L252

```
# plottree.R

  if (forestry_tree@linear) {
    # ridge forest
    for (leaf_id in node_info$node_id[node_info$is_leaf]) {
      # leaf_id = 5
      ###
      this_ds <- dta_x[leaf_idx[[leaf_id]],
                       forestry_tree@linFeats + 1]
      encoder <- onehot::onehot(this_ds)
      remat <- predict(encoder, this_ds)
      ###
      y_leaf <- dta_y[leaf_idx[[leaf_id]]]
      plm <- glmnet::glmnet(x = remat,
                            y = y_leaf,
                            lambda = forestry_tree@overfitPenalty * sd(y_leaf)/nrow(remat),
                            alpha	= 0)
```

As you said, `y_leaf` is a single element vector. `sd(y_leaf) = NA`, causing `lambda = NA`.

```
Browse[1]> n
debug at C:/Users/Linan Qiu/Desktop/temp.R#227: plm <- glmnet::glmnet(x = remat, y = y_leaf, lambda = forestry_tree@overfitPenalty * 
    sd(y_leaf)/nrow(remat), alpha = 0)
Browse[2]> forestry_tree@overfitPenalty * sd(y_leaf)/nrow(remat)
[1] NA
Browse[2]> sd(y_leaf)
[1] NA
Browse[2]> y_leaf
[1] -19.65548
```

**Comment by linanqiu** [comment]
For the case where you have the other error:

```
 Error in elnet(xd, is.sparse, ix, jx, y, weights, offset, type.gaussian,  : 
  y is constant; gaussian glmnet fails at standardization step 
```

The cause is still that couple of lines, but that's when `y_leaf` has length > 1 but consist of all the same elements:

```
overfitPenalty: 1
y_leaf: -9.56037240704544, -9.56037240704544, -9.56037240704544, sd(y_leaf): 0
nrow(remat): 3
```

Y is constant, which is what glmnet is complaining about. Could be because glmnet does some standardization (https://stackoverflow.com/questions/54755857/glmnet-error-nulldev-0-stopy-is-constant-gaussian-glmnet-fails-at-standa) and fails at `sd(y_leaf) = 0`

**Comment by sjsw** [comment]
This LGTM, Linan! :)
