### ISSUE TITLE
R crashes when linFeats is a singleton

### ISSUE THREAD

**Issue by sjsw** [forestry-labs/Rforestry#16]
Here's an example. Note that this code will cause R to crash. 

```
n <- c(100)
a <- rnorm(n)
b <- rnorm(n)
c <- rnorm(n)
y <- 4*a + 5.5*b - .78*c
x <- data.frame(a,b,c)

forest <- forestry(
  x,
  y,
  ntree = 10,
  replace = TRUE,
  maxDepth = 100,
  nodesizeStrictSpl = 10,
  nodesizeStrictAvg = 10,
  nthread = 2,
  linear = TRUE,
  linFeats = 1
)

predict(forest, aggregation = "oob")
```

**Comment by sjsw** [comment]
Since this works fine `predict(forest, x, aggregation = "oob")`. The issue is probably related to the code that constructs the training data when it is omitted from the call to forestry. 

There is also an error when we call plot(forest).

**Comment by sjsw** [comment]
I did make some progress on this here: https://github.com/forestry-labs/Rforestry/pull/18. I can add these changes in a new PR after yours is merged. One thing to note is that my fix for length(linFeats) == 1 only works against forestry 0.9.0.47 and not 0.9.0.52 as R crashes with 0.9.0.52 when fitting the forestry object with length(linFeats) == 1.  In any case, I'll hold off working on this until PR #17 is merged.

**Comment by linanqiu** [comment]
Closed by accident -- referred to this issue by accident
